version: '3'

services:
  python:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8000:8000
    volumes:
      - ./api:/app:Z
    networks:
      - backend
    env_file:
      - ./api/.env
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:15.3-alpine
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data:Z
      - ./migrations:/docker-entrypoint-initdb.d:Z
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: pi_dsm_5
      POSTGRES_USER: pi_dsm_5
      POSTGRES_DB: pi_dsm_5
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres

  rabbitmq:
    image: rabbitmq:3.11.18-management-alpine
    restart: on-failure
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq:Z
    networks:
      - backend
    environment:
      RABBITMQ_DEFAULT_USER: pi_dsm_5
      RABBITMQ_DEFAULT_PASS: pi_dsm_5
      RABBITMQ_DEFAULT_VHOST: mensageria_pi_dsm_5

networks:
  backend:
    driver: bridge
